name: send mail with slack

on: [push]

jobs:
  send-mail:
    runs-on: ubuntu-latest
    
    steps:
      - name: send
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          author_name: Github Action Test2
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
