name: learn-github-actions
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install -g bats
      - run: bats -v

# name: Java CI

# on: [push]

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v3
#       - name: Set up JDK 17
#         uses: actions/setup-java@v3
#         with:
#           java-version: '17'
#           distribution: 'temurin'
#       - name: Validate Gradle wrapper
#         uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3
#       - name: Build with Gradle
#         uses: gradle/gradle-build-action@749f47bda3e44aa060e82d7b3ef7e40d953bd629
#         with:
#           arguments: build

# # name: ci

# # on:
# #   push:
# #     branches:
# #       - "main"

# # jobs:
# #   build:
# #     runs-on: ubuntu-latest
# #     steps:
# #       -
# #         name: Checkout
# #         uses: actions/checkout@v3
# #       -
# #         name: build spirng
# #         uses: ./gradlew build
# #       -
# #         name: Login to Docker Hub
# #         uses: docker/login-action@v2
# #         with:
# #           username: ${{ secrets.DOCKERHUB_USERNAME }}
# #           password: ${{ secrets.DOCKERHUB_TOKEN }}
# #       -
# #         name: Set up Docker Buildx
# #         uses: docker/setup-buildx-action@v2
# #       -
# #         name: Build and push
# #         uses: docker/build-push-action@v4
# #         with:
# #           context: .
# #           file: ./Dockerfile
# #           push: true
# #           tags: ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
